name: Build

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@master
      - name: Generate cmake files
        shell: cmd
        run: |
          mkdir build && cd build
          cmake .. -G "Visual Studio 16 2019" -A Win32
      - name: Build
        run: |
          cmake --build build/ --config ${{ matrix.configuration }}
          Rename-Item -Path "build\${{ matrix.configuration }}\XbSymbolDatabaseTool.exe" -NewName "XbSymbolDatabaseTool.win64.${{ matrix.configuration }}.exe"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: XbSymbolDatabaseTool
          path: build/${{ matrix.configuration }}/XbSymbolDatabaseTool.win64.${{ matrix.configuration }}.exe

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@master
      - name: Generate cmake files
        run: |
          mkdir build && cd build
          cmake .. -G "Unix Makefiles"
      - name: Build
        run: |
          cmake --build build/ --config ${{ matrix.configuration }}
          mv build/XbSymbolDatabaseTool build/XbSymbolDatabaseTool.linux64.${{ matrix.configuration }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: XbSymbolDatabaseTool
          path: build/XbSymbolDatabaseTool.linux64.${{ matrix.configuration }}

  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@master
      - name: Generate cmake files
        run: |
          mkdir build && cd build
          cmake .. -G "Xcode"
      - name: Build
        run: |
          cmake --build build/ --config ${{ matrix.configuration }}
          mv build/${{ matrix.configuration }}/XbSymbolDatabaseTool build/${{ matrix.configuration }}/XbSymbolDatabaseTool.macos64.${{ matrix.configuration }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: XbSymbolDatabaseTool
          path: build/${{ matrix.configuration }}/XbSymbolDatabaseTool.macos64.${{ matrix.configuration }}
